"""Python client for the Preburn API."""

from preburn._async_client import AsyncCustomers, AsyncPreburn, AsyncRevenue
from preburn._client import Customers, Preburn, ReportMode, Revenue
from preburn._errors import (
    APIError,
    AuthenticationError,
    ConfigurationError,
    DecisionDenied,
    DecisionNotApplicableError,
    InvalidField,
    PreburnError,
    RateLimitError,
    ScopeError,
    ValidationError,
)
from preburn._models import (
    AttributeValue,
    CallContext,
    CostStatus,
    Customer,
    CustomerStatus,
    Decision,
    EstimateBasis,
    FallbackOutcome,
    FeatureSignals,
    Outcome,
    Reason,
    ReportFields,
    ReportResult,
    RevenueEntry,
    RevenueKind,
    RevenueSource,
    Signals,
)
from preburn._version import __version__

__all__ = [
    "APIError",
    "AsyncCustomers",
    "AsyncPreburn",
    "AsyncRevenue",
    "AttributeValue",
    "AuthenticationError",
    "CallContext",
    "ConfigurationError",
    "CostStatus",
    "Customer",
    "CustomerStatus",
    "Customers",
    "Decision",
    "DecisionDenied",
    "DecisionNotApplicableError",
    "EstimateBasis",
    "FallbackOutcome",
    "FeatureSignals",
    "InvalidField",
    "Outcome",
    "Preburn",
    "PreburnError",
    "RateLimitError",
    "Reason",
    "ReportFields",
    "ReportMode",
    "ReportResult",
    "Revenue",
    "RevenueEntry",
    "RevenueKind",
    "RevenueSource",
    "ScopeError",
    "Signals",
    "ValidationError",
    "__version__",
]
